FuelLabs/fuels-wallet

- package.json
- packages/app/cypress/e2e/CreateWallet.cy.ts
- packages/app/cypress/e2e/FaucetDialog.cy.ts
- packages/app/cypress/utils/test-utils.ts
- packages/app/src/config.ts
- packages/app/src/systems/Account/events.tsx
- packages/app/src/systems/Account/hooks/index.tsx
- packages/app/src/systems/Account/hooks/useAccounts.tsx
- packages/app/src/systems/Account/hooks/useIsLogged.tsx
- packages/app/src/systems/Account/machines/accountsMachine.tsx
- packages/app/src/systems/Core/components/PrivateRoute/PrivateRoute.tsx
- packages/app/src/systems/Core/components/PublicRoute/PublicRoute.tsx
- packages/app/src/systems/Faucet/machines/faucetMachine.tsx
- packages/app/src/systems/SignUp/components/WalletCreated/WalletCreated.tsx
- packages/app/src/systems/SignUp/machines/signUpMachine.ts
- packages/mediator/src/mediator.ts
> **Note**
>We still need localStorage to avoid users being redirected to /sign-up when reloading the page. Another way of doing this without needing the localStorage is by having a `<Spinner>` every time on `<PrivateRoute>`, but I think this is better to avoid spinners
> fix(app): improve check for private/public routes

- packages/app/src/systems/Core/components/Layout/Layout.tsx
The layout vertical padding was different from the design, making the content have a big gap on the top.
> fix: layout padding 

- packages/app/src/config.ts
- packages/app/src/routes.tsx
- packages/app/src/systems/Account/__mocks__/accounts.tsx
- packages/app/src/systems/Account/components/UnlockDialog/UnlockDialog.stories.tsx
- packages/app/src/systems/Account/components/UnlockDialog/UnlockDialog.tsx
- packages/app/src/systems/Account/components/UnlockDialog/index.tsx
- packages/app/src/systems/Account/components/UnlockForm/UnlockForm.tsx
- packages/app/src/systems/Account/components/UnlockForm/index.tsx
- packages/app/src/systems/Account/components/index.tsx
- packages/app/src/systems/Account/hooks/index.tsx
- packages/app/src/systems/Account/hooks/useAccount.tsx
- packages/app/src/systems/Account/hooks/useUnlockForm.tsx
- packages/app/src/systems/Account/machines/accountMachine.tsx
- packages/app/src/systems/Account/services/account.ts
- packages/app/src/systems/Core/components/Layout/TopBar.tsx
- packages/app/src/systems/Core/components/Mnemonic/Mnemonic.stories.tsx
✨ Fix #139
I spent some time trying to add E2E tests for this screen, but I had some problems
- There isn't a good way to mock or handle IndexedDB inside Cypress, we need to add the created vault inside the IndexedDB, then retrieve it using the `AccountService` to unlock the wallet and any of this is possible by using Cypress
- I gave it a try to Playwright as well, but it was getting `import.meta` error and I didn't find anything related on how to fix that or maybe change its bundler configuration.
- Also with Jest, I'm getting the same error I was getting in the past because of `fuels-ts`, something related to this:
So, I ended up with no options for this E2E test 😅
> feat(app): add Unlock dialog

- packages/app/src/systems/Core/machines/fetchMachine.test.ts
- packages/app/src/systems/Core/machines/fetchMachine.ts
- add `maxAttempts` option to fetchMachine, allowing it to be inputted instead of always being 3.
- fix retries running more times than expected
- add tests to the often used `fetchMachine.tsx`
Closes #149 
Closes #150 
Closes #151
> feat(fetchMachine): add `maxAttempts`

- packages/app/src/systems/Core/utils/route.ts
The stringifyUrl method was using the pathname, wich doesn't include the base URL, causing the faucet button not to include the URL when opening the faucet.
it was fixed by changing the use of the pathname to use href.
> fix: change stringifyUrl to use href instead of pathname

- packages/docs/src/hooks/useLoading.tsx
When FuelWeb3 was loaded all places that useLoading were not receiving the new FuelWeb3 reference.
> feat: add fuelweb on deps

- packages/app/src/store.tsx
- packages/app/src/systems/Account/machines/accountMachine.tsx
- packages/app/src/systems/Home/pages/Home/Home.stories.tsx
- packages/store/src/createStore.tsx
- packages/store/src/types.ts
```jsx
// before
const services = {
account: accountMachine
}
// after
const services = {
account: () => accountMachine
}
```
> fix(app): creation of services obj on store

- .changeset/curly-chicken-watch.md
- packages/docs/docs/typescript.mdx
- packages/docs/examples/Transfer.tsx
- packages/docs/src/constants.ts
- packages/docs/src/hooks/useFuelWeb3.tsx
- packages/docs/src/types.ts
- packages/sdk/package.json
- packages/sdk/src/FuelWeb3.test.ts
- packages/sdk/src/FuelWeb3.ts
- packages/sdk/src/__mock__/FuelWeb3.ts
- packages/sdk/src/index.ts
- packages/sdk/tsup.config.js
- packages/types/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
The following PR adds the ability for developers to import Fuel Wallet SDK types on the projects by,
installing `fules` and `@fuel-wallet/sdk` and importing `@fuel-wallet/sdk` on `tsconfig.json` or any `d.ts` file.
For type compatibility with `fuels` I have moved `fuels` to be a `peerDependency` instead of a hard `dependency` this makes the `Wallet SDK` compatible with any version of the `fuels` that the project has. Just respecting to be later than `0.23.0`.
This PR;
- Adds support for importing types on projects
- Change fuels from being a dependency to a peer dependency to create compatibility
- Add a new section on docs `TypeScript` to explain how to install and use it.
- Fix examples to work with the new types.
- Bundle types package on the build of SDK to avoid version issues. …
> fix: export types for the SDK

- packages/docs/src/components/Header.tsx
The main focus of the live docs is just the wallet usage and installation. The storybook is not related to it. Because of this, we should hide it on the main website.
> chore: remove storybook on docs production

- packages/app/playwright/e2e/ChangePassword.test.ts
- packages/app/src/systems/DApp/methods/transactionRequestMethods.ts
After tx was complete, the DApp was not receiving the event and closing as expected.
> fix: close window after tx is sent

- packages/app/playwright/e2e/Logout.test.ts
- packages/app/playwright/e2e/SelectWallet.test.ts
- packages/app/src/mocks/localStorage.ts
- packages/app/src/systems/Account/__mocks__/accounts.tsx
- packages/app/src/systems/Account/events.tsx
- packages/app/src/systems/Account/hooks/useAccounts.tsx
- packages/app/src/systems/Account/machines/accountMachine.test.ts
- packages/app/src/systems/Account/machines/accountMachine.tsx
- packages/app/src/systems/Account/pages/Logout/Logout.stories.tsx
- packages/app/src/systems/Account/pages/Logout/Logout.tsx
- packages/app/src/systems/Account/pages/Logout/index.tsx
- packages/app/src/systems/Account/pages/index.tsx
- packages/app/src/systems/Account/routes.tsx
- packages/app/src/systems/Account/services/account.ts
- packages/app/src/systems/Core/types.ts
- packages/app/src/systems/Sidebar/components/Sidebar/Sidebar.tsx
- packages/app/src/systems/Sidebar/constants/sidebarItems.ts
Add logout feature to Wallet. This action deletes all storage. I also added an intermediary page with warning content to confirm that users had backed up the seed phrase and the risk of deleting it.
closes: #380
> feat: add logout action

- package.json
- packages/app/src/systems/Account/pages/AddAccount/AddAccount.tsx
- packages/app/src/systems/Core/components/Providers/Providers.tsx
- packages/app/src/systems/Core/components/UnlockDialog/UnlockDialog.tsx
- packages/app/src/systems/DApp/pages/SignatureRequest/SignatureRequest.tsx
- packages/app/src/systems/DApp/pages/TransactionRequest/TransactionRequest.tsx
- packages/app/src/systems/Send/pages/SendPage/SendPage.tsx
- pnpm-lock.yaml
- make unlockDialog not fullscreen when browser is in fullscreen mode
- centralize app in `body` element: `margin: 0 auto`;
Closes #201 
Closes #199
> fix: make unlockDialog fullscreen only when the browser is not fullscreen

- packages/app/jest.setup.ts
When jest fails retry just the failed tests, this will avoid the need to manually retry tests.
> chore: add retry to jest tests

- packages/app/playwright/crx/crx.test.ts
- packages/app/src/systems/Account/services/account.ts
- packages/app/src/systems/CRX/background/services/BackgroundService.ts
- packages/app/src/systems/CRX/background/services/PopUpService.ts
- packages/app/src/systems/CRX/background/services/types.ts
- packages/app/src/systems/CRX/scripts/pageScript.ts
- packages/app/src/systems/DApp/hooks/useSignatureRequest.tsx
- packages/app/src/systems/DApp/hooks/useTransactionRequest.tsx
- packages/app/src/systems/DApp/machines/signMachine.test.tsx
- packages/app/src/systems/DApp/machines/signMachine.tsx
- packages/app/src/systems/DApp/machines/transactionMachine.test.tsx
- packages/app/src/systems/DApp/machines/transactionMachine.tsx
- packages/app/src/systems/DApp/methods/signRequestMethods.ts
- packages/app/src/systems/DApp/methods/transactionRequestMethods.ts
- packages/app/src/systems/DApp/pages/ConnectionRequest/ConnectionRequest.tsx
- packages/app/src/systems/DApp/pages/SignatureRequest/SignatureRequest.tsx
- packages/app/src/systems/DApp/pages/TransactionRequest/TransactionRequest.tsx
- packages/app/src/systems/Send/__mocks__/send.tsx
- packages/app/src/systems/Send/components/SendSelect/SendSelect.tsx
- packages/app/src/systems/Send/hooks/useSend.tsx
- packages/app/src/systems/Send/machines/sendMachine.ts
- packages/app/src/systems/Transaction/services/transaction.tsx
Add address-based `signMessage` and sendTransaction feature, with this PR it will be possible to execute actions with a different wallet that is not currently selected.
- Update machines `tranasactionRequest` and `signatureRequest`
- Add address param on start machine actions.
- Add a new state fetchAccount to query the account by the address
- On `tranasactionRequest` also add fetch balances as required it.
- Update machine `sendMachine`
-  To inform the address before starting the `transactionRequest` machine.
- Add E2E tests for this
- Fix machine tests to inform the address
close: #495
> feat: add address based feature for signMessage and sendTransaction

- .changeset/wet-gifts-love.md
- packages/docs/docs/api.mdx
- packages/docs/docs/how-to-use.mdx
- packages/docs/examples/SignMessage.tsx
- packages/sdk/src/Fuel.ts
- packages/sdk/src/FuelWalletConnection.ts
- packages/sdk/src/FuelWalletLocked.ts
- packages/sdk/src/FuelWalletProvider.ts
When doing a transaction without previously adding coins, the current solution could not detect the signer. For this, I have created a FuelWalletLocked that implements the sendTransaction and passes the provider the signer on the tx payload.
As we now have a custom wallet, I also add a sign message method to the instance of the wallet.
This PR;
- Adds a custom WalletLocked instance to the fuel instance.
- Adds docs using the `signMessage` from the FuelWalletLocked.
> fix: pass signer from wallet

- packages/app/package.json
- packages/app/vite-utils/vite.base.config.ts
- pnpm-lock.yaml
When developing the Wallet using `pnpm dev:crx` sometimes the code is not updated If you had previously executed a `pnpm build:app` because the files on `dist-crx` are not removed before the dev command starts.
This PR add a plugin to vite to remove the files on the folders dist and dist-crx before start the dev server, this is a not problem on build time as vite already cleans the folders.
> fix: delete dist-crx before run dev:crx

- packages/docs/docs/contributing/running-locally.mdx
- packages/docs/docs/how-to-use.mdx
- packages/docs/examples/Connect.tsx
- packages/docs/examples/CurrentAccount.tsx
- packages/docs/examples/ListAccounts.tsx
- packages/docs/examples/SignMessage.tsx
- packages/docs/examples/Transfer.tsx
- packages/docs/src/components/Link.tsx
- packages/docs/src/lib/code-import.ts
- packages/docs/src/pages/index.tsx
This PR;
- improves code example import migrating from lineStart and lineEnd to use comment blocks `/* example:start */` and
`/* example:end */`.
- Fix source code links. Currently, they are broken, pointing to the wrong link.
- Fix the footer navigator when entering on route `/` by changing to render to redirect to `/docs/install`.
- Fix repo links, now it's possible to use @repository on links that point to `https://github.com/FuelLabs/fuels-wallet/blob/master`
close: #537
> fix: home redirect, source code link and code import

- .changeset/tough-nails-compete.md
- packages/app/playwright/crx/crx.test.ts
- packages/docs/docs/api.mdx
- packages/docs/docs/how-to-use.mdx
- packages/docs/examples/events/Accounts.tsx
- packages/docs/examples/events/CurrentAccount.tsx
- packages/docs/examples/events/Network.tsx
- packages/docs/src/hooks/useIsConnected.tsx
- packages/sdk/src/Fuel.test.ts
- packages/sdk/src/Fuel.ts
- packages/sdk/src/FuelWalletConnection.ts
- packages/sdk/src/__mock__/Fuel.ts
- packages/types/src/fuel.ts
The implementation made on PR #526 has added events as an enum, but with this change, the user had to always import the Enum from the package in order to use it. The idea here is to externalize this enum directly on the fuel instance on the window.
> refactor: change `fuel.on` to accept string and externalize events on fuel instance

- packages/app/playwright/crx/crx.test.ts
- packages/app/src/systems/DApp/hooks/useTransactionRequest.tsx
- packages/app/src/systems/DApp/pages/TransactionRequest/TransactionRequest.tsx
- packages/app/src/systems/Transaction/components/TxContent/TxContent.tsx
- packages/app/src/systems/Transaction/components/TxFromTo/TxFromTo.test.tsx
- packages/app/src/systems/Transaction/components/TxFromTo/TxFromTo.tsx
- packages/app/src/systems/Transaction/components/TxOperation/TxOperation.tsx
- packages/app/src/systems/Transaction/components/TxOperations/TxOperations.tsx
This PR;
- Fix approval TX request by ignoring the tx popup on external requests;
- improve after approval screen to show just a loader instead of putting the entire state at a loading;
- Add a test to ensure tx approval from DApp opens the correct screen.
> feat: implement small improvements on the approve flow and tx approval

- .changeset/angry-mayflies-taste.md
- packages/app/src/systems/Account/machines/accountsMachine.tsx
[FRO-111](https://linear.app/fuel-network/issue/FRO-111/after-editing-a-account-the-account-list-should-be-refetch)
> fix: edit account refresh account list

- packages/docs/docsearch.json
Add all links for docsearch to index, the current approach was not indexing all pages as docsearch was not able to detect all paths related to `/`.
> feat: index all pages on docsearch

- packages/docs/docs/install.mdx
Simple update to the documentation
> docs: Fixing typo and indication (Developer switch is on the top right)

- .changeset/stale-knives-join.md
- packages/app/package.json
- packages/app/playwright/crx/crx.test.ts
- packages/app/playwright/mocks/database.ts
- packages/app/src/systems/Core/components/Mnemonic/Mnemonic.stories.tsx
- packages/app/src/systems/Send/machines/sendMachine.test.ts
- packages/app/src/systems/SignUp/components/MnemonicWrite/MnemonicWrite.test.tsx
- packages/app/src/systems/SignUp/machines/signUpMachine.ts
- pnpm-lock.yaml
- scripts/deps.sh
> chore: migrate dependencies from @fuel-ts/* to fuels

- .changeset/lazy-dingos-relate.md
- packages/sdk/src/connections/WindowConnection.ts
- packages/sdk/src/tests/FuelWalletConnectors.test.ts
Fix to the default Fuel Wallet connector functionality. When adding a connector we need to check the name of this connector instead of the currently selected connector
close #805
> fix: default connector Fuel Wallet

- .changeset/five-schools-turn.md
- packages/app/src/systems/Asset/hooks/useAssetForm.tsx
close: https://linear.app/fuel-network/issue/FRO-239
> fix: Asset Screen to allow empty img url

- .github/workflows/pr-tests.yml
- package.json
- packages/docs/docs/contributing/running-locally.mdx
currently our node commands are like:
normal node command `pnpm node:up` 
test node command `pnpm node:test:up`
I'm just changing the order and putting `test` as last param: `pnpm node:up:test` 
the reason is that "test" works like a modifier, almost a tag: `pnpm node --test` ...
if you're used to run `pnpm node:up` , the natural way for running the test command will be just adding the modifier at the end: `pnpm node:up:test`
> chore: put test as last params in node commands

- .changeset/giant-pears-doubt.md
- packages/docs/examples/Connectors.tsx
- packages/docs/src/hooks/useFuel.tsx
- packages/sdk/src/connections/WindowConnection.ts
- packages/sdk/src/tests/FuelWalletConnectors.test.ts
Currently, when using the SDK directly instead of window. Fuel, the connectors are not updated once they are available. This fix creates a syncing handler to ensure data is bonded between both. This will probably improve the communication protocol refactor. https://github.com/FuelLabs/fuels-wallet/issues/506
> fix: sdk connectors syncing

- .changeset/mean-trees-rescue.md
- packages/app/playwright/crx/crx.test.ts
- packages/app/src/systems/CRX/background/services/DatabaseEvents.ts
- packages/sdk/src/FuelWalletConnection.ts
- packages/types/src/fuel.ts
On this PR;
- Change `currentEvent` to notify when the account is not connected with a `null` value.
> feat: dispatch current account event with null when is not connected

- .changeset/nine-eggs-build.md
- packages/types/src/error.ts
Although `@fuel-wallet/types` does not specify React as a dependency, it still depends on react (specifically `@types/react`). If the library is used in a project that doesn't have `@types/react` installed, Typescript will give the following error:
```
node_modules/@fuel-wallet/types/src/error.ts:2:24 - error TS2307: Cannot find module 'react' or its corresponding type declarations.
2 import type React from 'react';
```
Given that the import is just a simple interface, I've copied the interface into the file and removed the import.
> fix: Remove unlisted dependency on React

- README.md
Old: https://wallet.fuel.network/docs/api/
New: https://wallet.fuel.network/docs/dev/getting-started/
> chore: Fix broken link for Wallet SDK

- .github/workflows/release-npm.yaml
- turbo.json
On this PR;
- On every release add to the release tag the development build of the fuel-wallet.
> ci: attach development build on release

- .changeset/gentle-melons-switch.md
- packages/app/e2e.html
- packages/app/index.html
- packages/app/popup.html
closes: #1029 
Based on the screenshots of the application, we could guess that the error happens because a kown issue with dom manipulation when using [translators](https://github.com/facebook/react/issues/11538).  For now I added the tags required to inform translators to not translate the page.
> fix: 'insertBefore' on 'Node' error by disabling translation

- .changeset/itchy-ducks-juggle.md
- package.json
- packages/react/src/ui/Connect/components/Connector/Connector.tsx
- packages/react/src/ui/Connect/components/ConnectorIcon.tsx
- packages/react/src/ui/Connect/components/Connectors/Connectors.tsx
- packages/react/src/ui/Connect/components/Connectors/styles.tsx
- packages/react/src/ui/Connect/utils/getImageUrl.tsx
- pnpm-lock.yaml
On this PR;
- Use the image url provided by the connector when a image svg is not found inside the component.
> feat: use connector image when icon is not available

- .changeset/shy-pandas-prove.md
- packages/app/playwright/e2e/RecoverWallet.test.ts
- packages/app/src/systems/Core/components/Mnemonic/Mnemonic.tsx
Automatically detect the length of a pasted seed phrase and adjust the selected format accordingly. 
If the size of the seed phrase does not match any predefined formats, the wallet will select the format that best fits the number of words.
- If the user pastes a `13-word` seed phrase, the wallet will select the `15-word` format and leave 2 blank inputs.
- If the user pastes a `24-word` seed phrase, it will select the `24-word` format and fill out all inputs.
- In cases where the size of the seed phrase exceeds the largest supported format or is smaller than the smallest supported format, appropriate handling is implemented to ensure consistent behavior.
Additionally, this PR includes support for `multi-line paste`, allowing users to input seed phrases with each word on a separate line.
| …
> feat: automatically update seed phrase size

- .changeset/tender-mails-float.md
- packages/app/src/systems/Account/components/AccountItem/AccountItem.tsx
- packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.tsx
It fixes https://github.com/FuelLabs/fuels-wallet/issues/1095
| Before | After |
|-------------|-------------|
| <img width="382" alt="Screenshot 2024-02-28 at 15 01 31" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/64ffe835-0d0d-43a3-a300-c30d8bbcb54b"> | <img width="374" alt="Screenshot 2024-02-28 at 15 01 19" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/3f97ff3a-19b9-4943-91eb-1103458fcbae"> |
> fix: display truncated account name correctly

- .changeset/three-wombats-hope.md
- packages/app/src/systems/Asset/components/AssetItem/AssetItem.tsx
- packages/app/src/systems/Asset/components/AssetList/AssetList.tsx
- packages/app/src/systems/Asset/pages/Assets/Assets.tsx
- packages/app/src/systems/Home/pages/Home/Home.tsx
This pull request memo the `Avatar` component, which avoids unnecessary rerendering when `imageUrl` is unchanged.
[before.webm](https://github.com/FuelLabs/fuels-wallet/assets/160697994/05275c41-fc8d-4ea2-ac09-186049b64203)
[after.webm](https://github.com/FuelLabs/fuels-wallet/assets/160697994/0af2c0d0-7c74-4f6f-9a79-c3a2ca40b4ea)
> perf: eliminating asset avatar flashing

- .github/workflows/release-changeset.yaml
Fixing this error:
`The workflow is not valid. .github/workflows/release-changeset.yaml: Unexpected tag '!steps.changesets.outputs.pullRequestNumber'`
> fix: adjust changeset condition

- .changeset/thick-feet-design.md
- packages/app/src/systems/Account/components/AccountList/AccountList.tsx
- packages/app/src/systems/Account/machines/addAccountMachine.tsx
- packages/app/src/systems/Account/machines/importAccountMachine.tsx
- packages/app/src/systems/Core/services/core.ts
- packages/app/src/systems/Settings/hooks/useExportVault.tsx
- packages/app/src/systems/Settings/machines/exportVaultMachine.test.tsx
- packages/app/src/systems/Settings/machines/exportVaultMachine.ts
- packages/app/src/systems/SignUp/services/signup.ts
- packages/app/src/systems/Vault/services/VaultServer.ts
Previously, `Wallet Manager` was failing to clear properly when `db.clear();` is called.
This led to wrong account addresses generation, as updates to the `IndexedDB` didn't reflect in the Wallet Manager's internal state, particularly the `#vaults` property.
To resolve this issue, I implemented a manual call to `removeVault` during logout. 
This ensures that each new wallet generated starts from scratch, free from interference by any previous mnemonic vault.
> fix: reset wallet manager to ensure correct generation of new accounts

- .changeset/rich-pens-wave.md
- packages/app/src/systems/Core/components/ConnectInfo/ConnectInfo.stories.tsx
- packages/app/src/systems/Core/components/ConnectInfo/ConnectInfo.tsx
- packages/app/src/systems/Core/utils/string.tsx
- packages/app/src/systems/Core/utils/url.ts
- packages/app/src/systems/DApp/pages/TransactionRequest/TransactionRequest.tsx
- packages/app/src/systems/Settings/components/ConnectionEdit/ConnectionEdit.tsx
- packages/app/src/systems/Settings/components/ConnectionItem/ConnectionItem.tsx
- Display the full app URL when it's big (instead of truncating it). Allowing the user to truly verify their connected apps.
- Sync the information displayed in the connected app `list` and `edit` screens to enhance consistency across our UI.
- Improve how the URL are displayed, focusing on the `hostname` mostly and use a native API instead of regex.
- Adjust the `Avatar` display to show only the first two initials letter when the page title is long (2+ words), preventing UI breakage.
|  List | Edit |
| --- | --- |
| <img width="345" alt="list" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/f4263c74-d211-493e-9beb-d42eaab247ba"> | <img width="346" alt="Screenshot 2024-03-26 at 17 22 40" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/33736052-9584-449c-9a19-afb81 …
> feat: sync UI between connected apps list and edit screens

- .changeset/five-buses-jump.md
- packages/app/src/systems/DApp/hooks/useTransactionRequest.tsx
- packages/app/src/systems/Transaction/hooks/useExplorerLink.tsx
- packages/app/src/systems/Transaction/pages/TxApprove/TxApprove.tsx
When the user is approving a transaction, the `id` is defined only on the `ctx.approvedTx`.
We can't say the same for the `ctx.txResult`, which has an undefined `id` in this flow.
I've updated to use that `id` when rendering the `TxApprove` screen.
Now the user can click to open the explorer properly.
> fix: add transaction id to the transaction approve page

- .changeset/short-feet-provide.md
- .lintstagedrc
- examples/cra-dapp/package.json
- packages/app/src/systems/Settings/components/ConnectionList/ConnectionList.tsx
- Fixes tooltip title text alignment.
- Replaces that orange `warning icon` with a gray `info circle icon`.
| ⚠️  Before |  ℹ️ After |
| ---- | ---- |
| <img width="335" alt="before" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/e32e8d25-22bb-45ed-8b1c-f0e6a6955ca2"> | <img width="332" alt="aftert" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/f6493205-68ad-4c72-8afe-f7867ce52cbe"> |
> chore: replace warning icon with a info circle icon on connected apps list

- .changeset/curly-lamps-work.md
- packages/app/src/systems/Transaction/pages/TxApprove/TxApprove.test.tsx
- packages/app/src/systems/Transaction/pages/TxApprove/TxApprove.tsx
Fixes #1201  
- Fixes loading state only being partially applied to TxApprove components
- Adds unit tests for TxApprove (as a dumb component)
https://github.com/FuelLabs/fuels-wallet/assets/3487334/60518df0-3b84-4d4c-881b-cc26dfc9b081
> fix: transaction approval screen showing odd half loading state

- .changeset/beige-olives-dress.md
- packages/app/src/systems/CRX/background/actions/autoUpdate.ts
Add listeners to ensure the update is downloaded and available, also check if the wallet is open if yes, schedule a reloadWallet for checking every 5 minutes.
> fix: auto-update reload action

- .gitattributes
Github recognizes Sway files and does not need them to be marked as Rust anymore.
> chore: Remove syntax highlighting of Sway files as Rust

- .changeset/tricky-socks-invite.md
- packages/app/src/systems/Core/utils/database.ts
- There are situations where the DB is closed and doesn't fire a close/blocked event, so I've implemented an interval that doas a health check and attempts to restart otherwise;
- Fixes extension side DB closing until extension reload after the Vault is locked, the browser hangs for a while and other edge cases scenarios where
Note: The DB is instantiated in both the extension's main thread and the service worker, we might want to refactor to instantiate and access it only in the service worker, using  Chrome's Messaging API as a communication layer with the main thread. It'd be safer and less problematic to debug than having 2 connections.
I'd suggest going to the `Send` screen (first screen after clicking send), filling out the form, waiting for the extension's lock time, then clicking …
> feat: implement database connection watcher

- .changeset/curvy-hotels-design.md
- packages/app/package.json
- packages/app/playwright/crx/crx.test.ts
- packages/app/playwright/e2e/Networks.test.ts
- packages/app/src/systems/Core/utils/database.ts
Rename ignition network to `Fuel Sepolia Testnet`.
| 📷  |
| --- |
| <img width="384" alt="Screenshot 2024-05-31 at 14 05 31" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/6235df60-82f6-45a2-9ff7-dc7ae17f49bc"> |
> feat: rename ignition network to fuel sepolia testnet

- packages/docs/docs/dev/hooks-reference.mdx
- packages/docs/spell-check-custom-words.txt
- packages/docs/src/components/BadgeDeprecated.tsx
- packages/docs/src/components/Code.tsx
- packages/docs/src/components/Provider.tsx
- Deprecate `useTransactionReceipts` in the documentation.
- Add `useTransactionResult` to the documentation.
| :camera: `useTransactionReceipts` |
| --- |
| <img width="1073" alt="Screenshot 2024-06-03 at 21 28 13" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/d4bd1b27-7457-4a75-ac1d-810a6bbe389b"> |
| :camera: `useTransactionResult` |
| --- |
| <img width="947" alt="Screenshot 2024-06-03 at 14 49 20" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/5d8f70b5-ad84-46fa-86aa-cb084d9bdb3e"> |
> docs: add useTransactionResult and deprecate useTransactionReceipts 

- .changeset/tidy-oranges-dream.md
- packages/app/src/systems/Transaction/components/ActivityItem/ActivityItem.tsx
> fix: transactionHistory list

- .changeset/pink-ties-report.md
- packages/app/src/systems/Network/utils/url.test.tsx
- packages/app/src/systems/Network/utils/url.tsx
With the previous regular expression, trying to parse a specifically malformed string would block the V8 thread (good catch @LuizAsFight!). More info on the issue can be read about [here](https://issues.chromium.org/issues/365066528).
- Optimized expression
- Added named matching groups
- Moved regular expression to be a global, avoiding instantiating it at the method's execution time
Closes #1460
> fix: extension freezing when validating a specifically malformed network URL

- .changeset/four-ladybugs-walk.md
- packages/app/src/systems/Unlock/machines/unlockMachine.tsx
> fix: show feedback when try to unlock with invalid password

- .changeset/tall-forks-poke.md
- packages/app/src/systems/Transaction/components/TxContent/TxContent.stories.tsx
- packages/app/src/systems/Transaction/components/TxContent/TxContent.tsx
- Closes https://github.com/FuelLabs/fuels-wallet/issues/1303
- Adds a few stories to highlight the changed behaviour
> chore: add copy button to errors header & stories

- .changeset/nine-frogs-carry.md
- .changeset/rotten-plums-leave.md
- packages/app/package.json
- packages/app/playwright/commons/text.ts
- packages/app/playwright/crx/crx.test.ts
- packages/app/playwright/e2e/Asset.test.ts
- packages/app/playwright/mocks/database.ts
- packages/app/src/systems/Asset/services/assets.ts
- packages/app/src/systems/CRX/background/services/BackgroundService.ts
- packages/app/src/systems/Core/types.ts
- packages/app/src/systems/Core/utils/route.test.ts
- packages/app/src/systems/Core/utils/route.ts
- pnpm-lock.yaml
- Fixed not being able to add a known token on a different network. Closes #1499 
- Fixed being able to manually create custom assets with duplicate asset ids. Closes #1503 
- Fixed routes not supporting optional parameters and not processing parameter values correctly in some instances. Closes #1511 
https://github.com/user-attachments/assets/77b3f24a-b7c4-42dc-ae6a-6f9916ca85b9
https://github.com/user-attachments/assets/8db99142-41a7-48df-a0bd-9f5f127dce84
> fix: custom assets addition and id duplication

- .changeset/great-suits-relax.md
- packages/app/src/systems/Asset/services/assets.ts
Closes #1501 
- Now listed assets are fetched from a verified network
> feat: use assets from verified network

- .changeset/swift-goats-cheat.md
- .changeset/tricky-roses-end.md
- packages/app/src/systems/CRX/scripts/contentScript.ts
- packages/app/src/systems/Vault/connectors/VaultCRXConnector.ts
- packages/app/src/systems/Vault/services/VaultClient.ts
Closes #1517 
- Moved `connection` prop from `VaultCRXConnector` to `Vault` client, as `VaultCRXConnector`'s `onRequest` method executes on `Vault`'s instance it'd fail to fetch the current `connected` data. 
- Added port disconnection detection and restart to `VaultCRXConnector`. Fixes wallet setup not finalizing
- Added missing parameter to destroy window listener on ContentScript when the page/tab is closed
> fix: wallet not communicating with vault during setup

- .github/workflows/release-npm-changeset.yaml
- Fixes using version of `Fuellabs/changesets` incompatible with our `@changeset/cli`
Evidence: https://github.com/FuelLabs/fuels-wallet/actions/runs/11151940944/job/30996473996
> fix: broken release rc action

- .changeset/gentle-insects-drum.md
- .changeset/tasty-deers-remain.md
- packages/app/src/systems/Core/utils/wallet.ts
- packages/app/src/systems/DApp/hooks/useTransactionRequest.tsx
- packages/app/src/systems/DApp/machines/transactionRequestMachine.tsx
- packages/app/src/systems/DApp/pages/TransactionRequest/TransactionRequest.FormProvider.tsx
- packages/app/src/systems/DApp/pages/TransactionRequest/TransactionRequest.tsx
- packages/app/src/systems/Send/components/SendSelect/SendSelect.tsx
- packages/app/src/systems/Send/hooks/useSend.tsx
- packages/app/src/systems/Send/machines/sendMachine.ts
- packages/app/src/systems/Transaction/components/TxContent/TxContent.stories.tsx
- packages/app/src/systems/Transaction/components/TxContent/TxContent.tsx
- packages/app/src/systems/Transaction/components/TxFeeOptions/TxFeeOptions.tsx
- packages/app/src/systems/Transaction/services/transaction.tsx
- packages/app/src/systems/Transaction/utils/gasLimit.ts
- Closes #1546 
- Simplified the estimation / approval part of the DAPP Approve Transaction screen
- Send transaction part
- Simulate transaction before sending, avoiding the user to spend gas in case of fail
- Skip estimating dependencies at this point, on this approval step we don’t wanna change the tx anymore
- Refact the transaction estimation part:
- Save the `initialTxRequest` as the one the dev first informed. All further changes will be always done based on this first tx informed
- Do the estimation, fee changes, funding if needed, and generate a `proposedTxRequest` which may have some changes
- this `proposedTxRequest` is gonna be the one to go for approval
- If the user choose to customize gas or tips, we apply again to the `initialTxRequest` and create a new …
> refactor: transaction estimation flow

- .changeset/breezy-glasses-double.md
- .changeset/fast-terms-glow.md
- packages/app/src/systems/CRX/background/services/PopUpService.ts
- packages/app/src/systems/CRX/scripts/executeContentScript.ts
- packages/connections/src/ContentProxyConnection.ts
- packages/types/src/contentScript.ts
- packages/types/src/index.ts
- Fixed duplicate instances of ContentScript after extension sleep/wakeup. Closes [#326](https://github.com/FuelLabs/fuel-connectors/issues/326)
- Ensure extension PopUp is closed on service resolve timeout/rejection.
- Ensure extension PopUp is closed on class destroy
> fix: duplicate instance of ContentScript causing black screen

- packages/e2e-contract-tests/playwright/e2e/DepositHalfEth.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardAndMintMulticall.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardEth.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardHalfAndExternalMint.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardHalfAndMint.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardHalfCustomAsset.test.ts
- packages/e2e-contract-tests/playwright/e2e/MintAsset.test.ts
- packages/e2e-contract-tests/playwright/e2e/utils/contract.ts
- packages/e2e-contract-tests/src/components/AssetConfigurationCard.tsx
- packages/e2e-contract-tests/src/components/DepositAndMintMultiCall.tsx
- packages/e2e-contract-tests/src/components/DepositHalfEthCard.tsx
- packages/e2e-contract-tests/src/components/ForwardCustomAssetCard.tsx
- packages/e2e-contract-tests/src/components/ForwardEthCard.tsx
- packages/e2e-contract-tests/src/components/ForwardHalfAndExternalMintCard.tsx
- packages/e2e-contract-tests/src/components/ForwardHalfAndMintCard.tsx
- packages/e2e-contract-tests/src/components/ForwardHalfCustomAssetCard.tsx
- packages/e2e-contract-tests/src/components/Header.tsx
- packages/e2e-contract-tests/src/components/MintAssetCard.tsx
- packages/e2e-contract-tests/src/hooks/useAction.ts
- Contract tests now display:
- Connection status
- Contract call errors below each field
- Buttons are now disabled when required data is not present
- Replaced `timeouts` with `expect.poll` using new visual indicators
> fix: flaky e2e contract tests

- .changeset/fresh-poets-count.md
- packages/app/package.json
- packages/app/playwright.config.ts
- packages/app/playwright/e2e/SendTransaction.test.ts
- packages/app/src/systems/Account/components/BalanceAssets/BalanceAssets.tsx
- packages/app/src/systems/Asset/cache/AssetsCache.ts
- packages/app/src/systems/Asset/components/AssetItem/AssetItem.tsx
- packages/app/src/systems/Asset/utils/assetId.ts
- packages/app/src/systems/Asset/utils/nft.ts
- packages/app/src/systems/Send/hooks/useSend.tsx
- packages/types/src/accounts.ts
- packages/types/src/asset.ts
- pnpm-lock.yaml
- Don't allow sending funds to assetId
- Improve logic of getting nft data
- Fix flaky test on transaction approval due to button entering/leaving loading state
> feat: improve nft support + dont send funds to assetId

- .changeset/lucky-trainers-heal.md
- packages/app/src/systems/Account/machines/accountsMachine.tsx
- packages/app/src/systems/Account/services/account.ts
- Closes: [#1666 ](https://linear.app/fuel-network/issue/FE-960/wallet-resetting-issue)
before
https://github.com/user-attachments/assets/f05c6721-6bb6-49b8-a30e-90f2101bba9a
after
https://github.com/user-attachments/assets/30989269-533d-4911-a540-845be34bdbc3
> fix: preventing wallet to reset because of fetch account returning undefined

- .changeset/heavy-nails-scream.md
- packages/app/src/systems/CRX/background/services/BackgroundService.ts
- packages/app/src/systems/CRX/background/services/DatabaseEvents.ts
- Closes https://github.com/FuelLabs/fuels-wallet/issues/1561
---
| 📷  Demo |
| --- |
| <video src="https://github.com/user-attachments/assets/8a445fa8-f508-41f3-95eb-6ed671ace618" /> |
> feat: fire event to dapps when editing current connection

- .changeset/long-jobs-kiss.md
- .changeset/tender-mails-crash.md
- packages/app/src/systems/Asset/components/AssetItem/AssetItem.tsx
- packages/app/src/systems/Asset/components/AssetItem/AssetItemAmount.tsx
- packages/app/src/systems/Transaction/services/transaction.tsx
- Closes https://github.com/FuelLabs/fuels-wallet/issues/1676
---
| 📷 Demo |
| --- |
| <img width="367" alt="Screenshot 2024-12-05 at 16 23 13" src="https://github.com/user-attachments/assets/08ed04e2-d97b-42b6-8802-8a25b7c5d66b"> |
> fix: feedback for insufficient ETH to cover transaction fees

- .changeset/brown-walls-rescue.md
- .changeset/cool-goats-teach.md
- .changeset/sharp-beans-exist.md
- .vscode/extensions.json
- .vscode/settings.json
- packages/app/src/systems/Account/hooks/useAccounts.tsx
- packages/app/src/systems/Account/machines/accountsMachine.tsx
- packages/app/src/systems/Account/services/account.ts
- packages/app/src/systems/Account/utils/storage.tsx
- packages/app/src/systems/Core/services/core.ts
- packages/app/src/systems/Core/utils/database.ts
- packages/app/src/systems/Core/utils/databaseNoDexie.ts
- Closes FE-1148
- refactor `accountMachine`
- should not have parallel states running between logout / fetchAccounts
- should have NOTHING to do with local storage prop `isLogged`
- move page reload to clear service, eliminating the possibility of anything running after it
- clear method wait for localStorage to be clean before reload
- now `isLogged` is set when opening the db
> fix: wallet reset issue

- .changeset/few-pants-marry.md
- package.json
- packages/app/package.json
- packages/docs/package.json
- packages/playwright-utils/package.json
- pnpm-lock.yaml
- Upgraded @fuels/ts-config and @fuels/tsup-config to version 0.26.0 in package.json files across multiple packages.
- Updated @fuels/local-storage to version 0.26.0 in package.json files for the app and playwright-utils.
- Adjusted pnpm-lock.yaml to reflect the new versions for consistency across the project.
> chore: update @fuels dependencies to version 0.26.0 (FIX FE-1221)

- .changeset/dry-days-flow.md
- .changeset/lemon-doors-protect.md
- packages/app/src/systems/DApp/machines/transactionRequestMachine.tsx
- packages/app/src/systems/Network/machines/chainInfoMachine.ts
- packages/app/src/systems/Send/machines/sendMachine.ts
- Closes #1770 
- Closes FE-1300
This PR also removes intentional delays that we had for a more smooth loading process
> fix: performance + approval page submit button entering on loading state

- .changeset/unlucky-vans-invent.md
- .github/workflows/pr-tests-jest.yml
- docker/Makefile
- docker/docker-compose.yml
- package.json
- packages/app/jest.config.ts
- packages/app/jest.setup.ts
- packages/app/package.json
- packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.test.tsx
- packages/app/src/systems/Account/machines/addAccountMachine.test.ts
- packages/app/src/systems/Account/machines/importAccountMachine.test.ts
- packages/app/src/systems/Account/services/account.test.ts
- packages/app/src/systems/Core/__tests__/utils/msw.ts
- packages/app/src/systems/Core/components/Mnemonic/Mnemonic.test.tsx
- packages/app/src/systems/Home/components/HomeActions/HomeActions.test.tsx
- packages/app/src/systems/Settings/components/ConnectionEdit/ConnectionEdit.test.tsx
- packages/app/src/systems/Settings/machines/settingsMachine.test.tsx
- packages/app/src/systems/Settings/pages/Connections/Connections.test.tsx
Closes: #1806 
Closes: FE-1428
- Set Jest to run tests in 4 shards
- Disabled retry and enabled multi-core executions by removing `maxWorkers: 1`
- Set MSW mock server to run when required on each test file, instead of once for the entire test duration
- Removed steps from jest CI that are not required
- Disable Jest Coverage as it adds overhead and is no longer used
- Tests now run in parallel and in arm archtecture
> fix: jest unit tests

- .github/workflows/release-npm-changeset.yaml
- Closes FE-1451
- Split release workflow into multiple jobs for better separation of concerns
- Add job to check if the current commit is from a changeset PR
- Create separate jobs for creating changeset PRs and publishing to npm
- Improve workflow logic to handle different release scenarios
> ci: refactor release workflow to separate changeset and publish jobs

- .github/workflows/release-npm-changeset.yaml
These changes are meant so that the create-pr action doesnt use the `npm-deploy`environment, therefore not needing the action permission to run, while keeping the permission requirement for the NPM dpeloy action.
> ci: update release workflow permissions and remove npm setup

- .github/workflows/release-npm-changeset.yaml
- Closes FE-1452
Fix conditionals that were deciding if release on NPM or push to the changeset PR
> fix: release action conditional

- .changeset/giant-frogs-develop.md
- packages/app/src/systems/Core/utils/convertToUsd.test.ts
- packages/app/src/systems/Core/utils/convertToUsd.ts
- Closes #1862 
- Closes FE-1491
Fix USD calculation and add unit tests to ensure we'll not face it again.
| 📷 Demo |
| --- |
| <img width="396" alt="Screenshot 2025-02-25 at 20 37 18" src="https://github.com/user-attachments/assets/59abe892-4282-49a9-a31a-d0f75cffd920" /> |
> fix: usd precision

- .changeset/warm-otters-sleep.md
- packages/app/src/systems/Account/components/EthAddress/EthAddress.tsx
- packages/app/src/systems/Asset/components/AssetSelect/AssetSelect.tsx
- packages/app/src/systems/Send/components/SendSelect/SendSelect.tsx
- packages/app/src/systems/Transaction/components/TxOperation/TxOperationCard.tsx
- packages/app/src/systems/Transaction/pages/TxApprove/TxApprove.tsx
- packages/app/src/systems/Transaction/services/transaction.tsx
- packages/app/src/systems/Transaction/services/transformers/simplifyTransaction.ts
- Closes #1877
- Closes #1876
- Closes FE-1554
- Closes FE-1553
- Improve sorting of Send Page assets (verified first, then nfts, then unknown assets, etc..)
- Show "Withdraw" operation when it has MESSAGE_OUT receipt
> feat: show Withdraw operation when it has MESSAGE_OUT receipt + improve order of assets in Send Page

- .changeset/dirty-planes-tie.md
- packages/app/src/systems/DApp/machines/transactionRequestMachine.tsx
- packages/app/src/systems/Transaction/services/transaction.tsx
- Closes FE-Z
The summary validation logic had a logic flaw.
> fix: include dryRun before showing transaction on approval screen coming from dapp

- .changeset/twenty-peas-reply.md
- packages/app/src/systems/CRX/background/services/BackgroundService.ts
- packages/app/src/systems/CRX/background/services/PopUpService.ts
- packages/app/src/systems/CRX/background/services/types.ts
- packages/app/src/systems/Core/utils/wallet.ts
- packages/app/src/systems/DApp/hooks/useTransactionRequest.tsx
- packages/app/src/systems/DApp/machines/transactionRequestMachine.tsx
- packages/app/src/systems/DApp/methods.ts
- packages/app/src/systems/DApp/pages/TransactionRequest/TransactionRequest.tsx
- packages/app/src/systems/Transaction/components/TxContent/TxContent.tsx
- packages/app/src/systems/Transaction/components/TxReviewAlert/TxReviewAlert.tsx
- packages/app/src/systems/Transaction/pages/TxApprove/TxApprove.tsx
- packages/app/src/systems/Transaction/services/transaction.tsx
Related: https://github.com/FuelLabs/fuel-connectors/pull/523
- Closes FE-1653
This PR introduces a new `signTransaction` method to the wallet's background service and DApp communication layer. This allows dApps to request a transaction signature without the wallet immediately broadcasting it.
**Key Changes:**
*   **`BackgroundService.ts`**:
*   Added a `signTransaction` method that leverages the existing `sendTransaction` popup UI flow.
*   It passes a `noSendReturnPayload: true` flag to `PopUpService.sendTransaction`.
*   **`PopUpService.ts`**:
*   The `sendTransaction` method now (implicitly via DApp methods) handles the `noSendReturnPayload` flag. 
*   **`DApp/methods.ts`**:
*   The `sendTransaction` method (handling requests from the popup) now checks for `noSendReturnPayload`.
* …
> feat: Implement signTransaction method for no-broadcast signing
