- package.json
- packages/app/.storybook/main.js
- packages/app/package.json
- turbo.json
- vercel.json
Create a command to build app and storybook under the same domain;
`/` render app
`/storybook` renders the storybook
> ci: add preview build command

- packages/app/.storybook/main.js
- packages/app/jest.config.ts
- packages/app/load.envs.js
- packages/app/src/systems/Core/utils/math.test.ts
- packages/app/vite.config.ts
This was made to enable the storybook to import env variables
> ci: change load envs config

- packages/app/vite.config.ts
> fix(app): support bigint on vite with target es2020

- packages/app/src/systems/Account/components/AccountItem/AccountItem.tsx
- packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.stories.tsx
- packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.tsx
- packages/app/src/systems/Account/components/BalanceWidget/BalanceWidgetLoader.tsx
- packages/app/src/systems/Account/types.ts
- packages/app/src/systems/Core/components/VisibilityButton/VisibilityButton.stories.tsx
- packages/app/src/systems/Core/components/VisibilityButton/VisibilityButton.tsx
- packages/app/src/systems/Core/components/VisibilityButton/index.tsx
- packages/app/src/systems/Core/components/index.tsx
> feat: add BalanceWidget component

- packages/app/cypress/e2e/RecoverWallet.cy.ts
- packages/app/package.json
- packages/app/src/systems/SignUp/machines/signUpMachine.ts
- pnpm-lock.yaml
> fix(app): recover wallet flow

- package.json
- pnpm-lock.yaml
temporary fix for #251 
`pnpm storybook` is working now, but we should track and remove the new `override` for `enhanced-resolve` after it gets fixed.
more info in the mentioned issue
> fix: pnpm storybook broken after clean install

- packages/app/src/systems/Asset/components/AssetsAmount/AssetsAmount.stories.tsx
- packages/app/src/systems/Asset/components/AssetsAmount/AssetsAmount.test.tsx
- packages/app/src/systems/Asset/components/AssetsAmount/AssetsAmount.tsx
- packages/app/src/systems/Asset/components/AssetsAmount/AssetsAmountLoader.tsx
- packages/app/src/systems/Transaction/components/TxHeader/TxHeader.test.tsx
> feat: add AssetAmount loader

- packages/app/src/systems/Transaction/components/TxDetails/TxDetails.stories.tsx
- packages/app/src/systems/Transaction/components/TxDetails/TxDetails.test.tsx
- packages/app/src/systems/Transaction/components/TxDetails/TxDetails.tsx
- packages/app/src/systems/Transaction/components/TxDetails/TxDetailsLoader.tsx
> feat: add TxDetails Loader

- packages/app/playwright/e2e/CreateWallet.test.ts
- packages/app/playwright/e2e/RecoverWallet.test.ts
- packages/app/src/systems/Core/components/ControlledField/ControlledField.test.tsx
- packages/app/src/systems/SignUp/components/MnemonicRead/MnemonicRead.tsx
- packages/app/src/systems/SignUp/components/MnemonicWrite/MnemonicWrite.tsx
> chore: fix typo on signup page

- packages/docs/docs/install.mdx
revising many typos. It looks like you are using some kind of machine translating to get the English version?
> docs: update install.mdx fix typos

- packages/docs/docs/api.mdx
- packages/docs/docs/how-to-use.mdx
Update docs to follow patterns. Change the order of sections and remove them from the how-to.
> feat: update docs

- packages/docs/src/components/MobileMenu.tsx
Remove storybook link on production
> chore: remove storybook on production sidebar

- packages/app/src/systems/Account/services/account.ts
> fix: remove unkown assets from the balance list

- .github/workflows/assign-project.yaml
Change APP_ID from using secrets to use vars.
> ci: change secret to vars

- .changeset/four-scissors-join.md
- packages/sdk/src/index.ts
> fix: Export FuelWalletLocked on package sdk

- packages/app/src/systems/Account/machines/accountMachine.test.ts
- packages/app/src/systems/Account/services/account.ts
- packages/app/src/systems/Core/utils/database.ts
The current database clear deletes the database what can cause issues, this refactor implements a better method that only clears all data.
> refactor: change database clear method

- .changeset/lucky-frogs-turn.md
Remove asset-list from the changelog files
> fix: changeset files

- packages/asset-list/package.json
Make asset-list package private
> chore: make asset-list private

- packages/app/playwright/crx/crx.test.ts
- packages/app/playwright/e2e/CreateWallet.test.ts
- packages/app/src/systems/SignUp/components/MnemonicRead/MnemonicRead.test.tsx
- packages/app/src/systems/SignUp/components/MnemonicRead/MnemonicRead.tsx
> feat: change checkboxes on signup mnemonic phrase screen

- .changeset/thick-lamps-reflect.md
- .github/workflows/pr.yaml
- packages/app/src/systems/CRX/background/services/PopUpService.ts
> fix: type change text

- README.md
> chore: update features

- .changeset/sour-trains-think.md
- packages/app/src/systems/Network/components/NetworkForm/NetworkForm.tsx
- packages/app/src/systems/Network/hooks/useNetworkForm.ts
> chore: modified network url validation rule

- .changeset/honest-colts-tan.md
- packages/docs/examples/AddAssets.tsx
- packages/docs/examples/Connect.tsx
- packages/docs/examples/CurrentAccount.tsx
- packages/docs/examples/ListAccounts.tsx
- packages/docs/examples/ListAssets.tsx
- packages/docs/examples/SignMessage.tsx
- packages/docs/examples/Transfer.tsx
> feat: move console.debug to console.log in docs

- .changeset/pink-tigers-wonder.md
- packages/sdk/package.json
> fix: wallet sdk exports

- .changeset/eight-horses-scream.md
- packages/app/src/systems/Core/utils/wallet.ts
- packages/app/src/systems/Transaction/__mocks__/tx.ts
- packages/app/src/systems/Transaction/utils/tx.test.ts
- packages/app/src/systems/Transaction/utils/tx.ts
> fix: transfer from inputMessage

- packages/docs/src/components/Header.tsx
- packages/docs/src/components/InstallSection.tsx
- packages/docs/src/constants.ts
- Fix header to also open chrome webstore on productions.
- Add button to download current preview zip on the header
> fix: header and add buttons on preview

- packages/docs/src/components/Header.tsx
change env var from NEXT_PUBLIC_DOWNLOAD_URL to NEXT_PUBLIC_WALLET_DOWNLOAD_URL
> fix: download on preview link

- .changeset/polite-phones-relate.md
- packages/sdk/src/connections/BaseConnection.ts
close: https://linear.app/fuel-network/issue/FRO-367
> fix: SDK request/response conflicts

- .changeset/blue-eggs-try.md
- packages/app/.env.production
- packages/app/playwright/e2e/Networks.test.ts
- packages/app/playwright/mocks/database.ts
- packages/app/src/systems/Asset/components/AssetRemoveDialog/AssetRemoveDialog.tsx
- packages/app/src/systems/Asset/pages/Assets/Assets.tsx
- packages/app/src/systems/Network/utils/url.test.tsx
- packages/sdk/src/tests/constants.ts
closes: FRO-433
In this PR;
- Fix the assets page to create a scroll when we have more them 5 assets on the page
- FIx Dialog overlay to have 100% width
> fix: assets scroll

- .changeset/nasty-poets-greet.md
- packages/app/package.json
- packages/app/src/systems/DApp/hooks/useTransactionRequest.tsx
- packages/app/src/systems/Transaction/__mocks__/transaction.tsx
- packages/app/src/systems/Transaction/__mocks__/tx.ts
- packages/app/src/systems/Transaction/components/ActivityItem/ActivityItem.stories.tsx
- packages/app/src/systems/Transaction/components/TxContent/TxContent.tsx
- packages/app/src/systems/Transaction/components/TxFromTo/TxFromTo.stories.tsx
- packages/app/src/systems/Transaction/components/TxFromTo/TxFromTo.test.tsx
- packages/app/src/systems/Transaction/components/TxFromTo/TxFromTo.tsx
- packages/app/src/systems/Transaction/components/TxHeader/TxHeader.stories.tsx
- packages/app/src/systems/Transaction/components/TxHeader/TxHeader.test.tsx
- packages/app/src/systems/Transaction/components/TxHeader/TxHeader.tsx
- packages/app/src/systems/Transaction/components/TxIcon/TxIcon.tsx
- packages/app/src/systems/Transaction/components/TxOperation/TxOperation.stories.tsx
- packages/app/src/systems/Transaction/components/TxOperation/TxOperation.tsx
- packages/app/src/systems/Transaction/components/TxOperations/TxOperations.stories.tsx
- packages/app/src/systems/Transaction/components/TxOperations/TxOperations.tsx
- packages/app/src/systems/Transaction/components/TxStatusAlert/TxStatusAlert.stories.tsx
- packages/app/src/systems/Transaction/components/TxStatusAlert/TxStatusAlert.test.tsx
- packages/app/src/systems/Transaction/components/TxStatusAlert/TxStatusAlert.tsx
- packages/app/src/systems/Transaction/hooks/useContractIds.tsx
- packages/app/src/systems/Transaction/services/transaction.tsx
- packages/app/src/systems/Transaction/types.tsx
- packages/app/src/systems/Transaction/utils/color.ts
- packages/docs/package.json
- packages/sdk/package.json
- packages/types/package.json
- pnpm-lock.yaml
> feat: update fuels sdk

- .github/workflows/release-npm.yaml
fix the issue with ci release: https://github.com/FuelLabs/fuels-wallet/actions/runs/5970105099/job/16214354397
> ci: move from secrets to vars

- .changeset/lazy-weeks-pretend.md
- packages/app/src/mocks/server.ts
- packages/app/src/systems/Transaction/__mocks__/chain.tsx
- packages/app/src/systems/Transaction/components/TxContent/TxContent.tsx
- packages/app/src/systems/Transaction/hooks/useTxResult.tsx
- packages/app/src/systems/Transaction/machines/transactionMachine.test.tsx
- packages/app/src/systems/Transaction/machines/transactionMachine.tsx
- packages/app/src/systems/Transaction/pages/TxView/TxView.tsx
- packages/sdk/src/utils/provider.ts
> fix: improve tx loader

- .changeset/bright-carrots-allow.md
- packages/app/playwright/e2e/SendTransaction.test.ts
- packages/app/src/systems/Transaction/services/transaction.tsx
- packages/app/src/systems/Transaction/utils/fee.ts
- packages/sdk/src/utils/provider.ts
> fix: fee calculation

- packages/e2e-contract-tests/playwright/e2e/DepositHalfEth.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardAndMintMulticall.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardCustomAsset.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardEth.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardHalfAndMint.test.ts
- packages/e2e-contract-tests/playwright/e2e/ForwardHalfCustomAsset.test.ts
- packages/e2e-contract-tests/playwright/e2e/MintAsset.test.ts
- packages/e2e-contract-tests/src/App.tsx
- packages/e2e-contract-tests/src/components/DepositAndMintMultiCall.tsx
- packages/e2e-contract-tests/src/components/index.tsx
- packages/e2e-contract-tests/src/contract_interactions/custom_asset_interactions.ts
- packages/test-utils/src/test-utils/fuelWallet.ts
> test: deposit and mint multicall

- .changeset/eleven-swans-tap.md
- packages/react/src/components/FuelProvider.tsx
- packages/react/src/config.ts
- packages/react/src/hooks/useConnect.tsx
- packages/react/src/hooks/useConnectors.tsx
- packages/react/src/utils/index.ts
- packages/react/src/utils/queryKeys.ts
- packages/react/src/utils/selectCurrenctConnector.ts
- packages/react/src/utils/selectCurrentConnector.ts
- packages/sdk/src/connections/WindowConnection.ts
On this PR;
- Add a listener to connectors to ensure once the current connector is available, select to connector.
> fix: load connectors

- .changeset/six-swans-wash.md
- packages/app/jest.setup.ts
- packages/app/package.json
- packages/app/src/systems/Transaction/services/transaction.tsx
- packages/docs/package.json
- packages/e2e-contract-tests/package.json
- packages/e2e-contract-tests/src/utils/assetId.ts
- packages/react/package.json
- packages/sdk/package.json
- packages/sdk/src/Fuel.ts
- packages/test-utils/package.json
- packages/types/package.json
- pnpm-lock.yaml
> fix: update fuels and fix build errors

- .changeset/long-actors-wonder.md
- packages/react/package.json
- packages/react/tsconfig.json
- packages/sdk/package.json
- packages/types/src/index.ts
- pnpm-lock.yaml
> fix: types dependencies on react and sdk packages

- packages/docs/docs/contributing/guide.mdx
> docs: add changeset documentation

- .changeset/nice-lizards-reply.md
- packages/app/package.json
- packages/app/src/config.ts
- packages/app/src/systems/CRX/background/services/BackgroundService.ts
- packages/app/src/systems/Network/__mocks__/networks.ts
- packages/app/src/systems/Network/services/network.ts
- pnpm-lock.yaml
> fix: check supported network version

- .changeset/neat-walls-turn.md
- packages/app/src/systems/Core/utils/assets.tsx
> refactor: use asset package

- .changeset/old-planets-provide.md
- packages/app/package.json
- packages/connections/package.json
- packages/docs/package.json
- packages/e2e-contract-tests/contracts/custom_asset/Forc.toml
- packages/e2e-contract-tests/contracts/custom_asset/src/main.sw
- packages/e2e-contract-tests/package.json
- packages/e2e-contract-tests/src/contract-ids.json
- packages/e2e-contract-tests/src/contracts/contracts/CustomAssetAbi.d.ts
- packages/e2e-contract-tests/src/contracts/contracts/CustomAssetAbi.hex.ts
- packages/e2e-contract-tests/src/contracts/contracts/common.d.ts
- packages/e2e-contract-tests/src/contracts/contracts/factories/CustomAssetAbi__factory.ts
- packages/e2e-contract-tests/src/contracts/contracts/index.ts
- packages/react/package.json
- packages/sdk/package.json
- packages/test-utils/package.json
- packages/types/package.json
- pnpm-lock.yaml
> chore: update fuels to 0.73.0

- .changeset/chilled-seahorses-brush.md
- examples/cra-dapp/package.json
- packages/app/package.json
- packages/docs/package.json
- packages/e2e-contract-tests/package.json
- pnpm-lock.yaml
✨ This PR updates the SDK to tag latest
> feat: updating sdk to latest

- .changeset/lovely-balloons-behave.md
- packages/app/package.json
- packages/app/playwright/e2e/ChangePassword.test.ts
- packages/app/src/systems/Settings/pages/ChangePassword/ChangePassword.tsx
- packages/e2e-contract-tests/package.json
- pnpm-lock.yaml
Fixes #1203 
- Prevents change password dialog from allowing the new password from being the same as the current password
| Before     | After |
| ---      | ---       |
| <img width="348" alt="Screenshot 2024-04-08 at 20 27 43" src="https://github.com/FuelLabs/fuels-wallet/assets/3487334/18fd7bb8-a52a-4d03-ac58-94a01ccf72c2"> | <img width="345" alt="Screenshot 2024-04-08 at 20 26 12" src="https://github.com/FuelLabs/fuels-wallet/assets/3487334/969dae7f-72ac-4d67-8a5b-699d91a65fa7"> |
> fix: Change Password dialog allowing new password to be the same as current #1203

- .changeset/shy-islands-fail.md
- .github/workflows/release-changeset.yaml
- packages/connections/package.json
> fix: release

- .github/workflows/release-changeset.yaml
Skipping Wallet build when it's not a release.
> fix: skip ci build

- packages/docs/src/components/Provider.tsx
> chore: include Fuelet on doc of connectors UI

- .changeset/sixty-grapes-repeat.md
- .github/CODEOWNERS
ps: this PR also includes a changeset to create a new release
> chore: update codeowners

- .changeset/red-apes-refuse.md
- packages/app/src/systems/Error/utils/parseFuelError.ts
- Closes #1381 
Improved error handling to avoid loose information before send it to sentry
Including location informations for better understanding the possible causes of error
> fix: handling error format to improve further sentry identification

- .changeset/gold-turtles-explain.md
- packages/app/src/systems/DApp/machines/addNetworkRequestMachine.tsx
- packages/app/src/systems/Network/machines/networksMachine.ts
- packages/app/src/systems/Network/services/network.ts
- Closes https://github.com/FuelLabs/fuels-wallet/issues/1436
---
| 📷 Demo |
| --- |
| <video src="https://github.com/user-attachments/assets/3d67e709-1ac4-44ca-9f44-feec93e9f041" /> |
> fix: add default networks regardless if they're down

- .github/workflows/release-npm-changeset.yaml
- packages/e2e-contract-tests/package.json
- packages/playwright-utils/CHANGELOG.md
- packages/playwright-utils/package.json
- packages/playwright-utils/src/fixtures/downloadFuel.ts
- packages/playwright-utils/src/fixtures/fixtures.ts
- packages/playwright-utils/src/fixtures/index.ts
- packages/playwright-utils/src/index.ts
- packages/playwright-utils/src/mocks/index.ts
- packages/playwright-utils/src/playwright-utils/button.ts
- packages/playwright-utils/src/playwright-utils/fuelWalletTestHelper.ts
- packages/playwright-utils/src/playwright-utils/index.ts
- packages/playwright-utils/src/playwright-utils/locator.ts
- packages/playwright-utils/src/playwright-utils/seedWallet.ts
- packages/playwright-utils/src/playwright-utils/text.ts
- packages/playwright-utils/src/playwright-utils/visit.ts
- packages/playwright-utils/src/utils/address.ts
- packages/playwright-utils/src/utils/index.ts
- packages/playwright-utils/tsconfig.json
- packages/playwright-utils/tsup.config.js
- pnpm-lock.yaml
> feat: include playwright-utils

- .changeset/hot-bees-love.md
- packages/app/src/systems/Core/services/core.ts
> chore: add success feedback when resetting the wallet

- .changeset/nasty-seals-hug.md
- packages/app/src/systems/Core/utils/databaseVersioning.ts
> fix: chainId not been indexed

- .changeset/purple-spoons-rule.md
- packages/app/package.json
- packages/app/src/systems/Asset/components/AssetSelect/AssetSelect.tsx
- pnpm-lock.yaml
- Closes https://github.com/FuelLabs/fuels-wallet/issues/1547
--- 
Add a simple scrollable container to the asset list.
| 📷  Demo |
| --- |
| <img width="375" alt="Screenshot 2024-10-03 at 16 43 58" src="https://github.com/user-attachments/assets/fffa7583-8a42-4175-acbf-1d2e4f746c48"> |
> fix: asset list scrollable container

- .changeset/poor-cobras-hug.md
- packages/app/playwright/crx/crx.test.ts
- packages/app/src/systems/CRX/background/services/BackgroundService.ts
- Closes https://github.com/FuelLabs/fuel-connectors/issues/352
- Closes FE-695
> feat: make wallet return currentAccount even if the wallet account is not selected

- .husky/pre-commit
- packages/docs/docs/install.mdx
- packages/docs/src/components/DownloadWalletZip.tsx
also adding nvm config to pre-commit file due to pnpm command failing
> chore: change zip file name on docs site

- .changeset/perfect-bees-return.md
- packages/app/src/systems/DApp/pages/SignatureRequest/SignatureRequest.tsx
> chore: break line of signMessage

- .changeset/dull-tomatoes-breathe.md
- packages/app/playwright/crx/crx.test.ts
- packages/app/src/systems/Asset/components/AssetsAmount/AssetsAmount.tsx
- packages/app/src/systems/Asset/components/AssetsAmount/styles.ts
| 📷  Demo |
| --- |
| <img width="331" alt="review" src="https://github.com/user-attachments/assets/63847bd5-1edd-477d-874c-8c8be5266c69"> |
> fix: display truncated amounts

- .changeset/red-llamas-travel.md
- .github/workflows/pr-tests-e2e-crx-lock.yml
- packages/app/playwright/crx/lock.test.ts
- packages/app/src/systems/CRX/background/services/VaultService.ts
- Closes https://github.com/FuelLabs/fuels-wallet/issues/1356
- Added E2E to ensure auto-lock behavior.
> fix: reset auto-lock timer if the vault service is running

- .github/CODEOWNERS
- Removes @pedronauck from code owners
> chore: remove pedro from code owners

- .changeset/two-starfishes-double.md
- packages/app/src/systems/Core/components/InputAmount/InputAmount.tsx
- packages/app/src/systems/Core/components/InputAmount/InputAmount.utils.ts
- packages/app/src/systems/Send/components/SendSelect/SendSelect.tsx
- packages/app/src/systems/Send/hooks/useSend.tsx
- packages/app/src/systems/Send/machines/sendMachine.ts
- packages/app/src/systems/Send/pages/SendPage/SendPage.tsx
- packages/app/src/systems/Transaction/components/TxFeeOptions/TxFeeOptions.tsx
- Closes #1770 
- Closes FE-1300
> fix: Send screen more stable

- .changeset/breezy-gorillas-lick.md
- packages/app/playwright/e2e/Accounts.test.ts
- packages/app/src/systems/Account/hooks/useImportAccountForm.ts
- Closes #1803 
- Closes FE-1418
> feat: prevent users from importing public keys as private

- .changeset/famous-phones-live.md
- packages/types/src/fuel.ts
Just bump the version to run changeset
> chore: bump version

- .changeset/cool-teachers-drive.md
- packages/app/playwright/commons/logout.ts
- packages/app/playwright/crx/crx.test.ts
- packages/app/playwright/crx/lock.test.ts
- Closes #1853 
- Closes FE-1460
> test: improve timeout handling and page navigation in e2e tests

- .changeset/polite-toys-enjoy.md
- packages/app/src/systems/Core/utils/convertToUsd.test.ts
- packages/app/src/systems/Core/utils/convertToUsd.ts
- Closes #1862 
- Closes FE-1491
Fix USD calculation and add unit tests to ensure we'll not face it again.
| 📷 Demo |
| --- |
| <img width="396" alt="Screenshot 2025-02-25 at 20 37 18" src="https://github.com/user-attachments/assets/59abe892-4282-49a9-a31a-d0f75cffd920" /> |
> fix: usd calculation

- .changeset/eight-beers-attend.md
- .changeset/unlucky-bulldogs-hunt.md
- examples/cra-dapp/package.json
- packages/app/package.json
- packages/app/src/systems/Transaction/components/TxReviewAlert/TxReviewAlert.tsx
- packages/app/src/systems/Transaction/services/transformers/simplifyTransaction.ts
- pnpm-lock.yaml
> chore: fix typo + audit

- .changeset/tidy-lamps-argue.md
- packages/app/playwright.config.ts
- packages/app/src/systems/DApp/pages/SignatureRequest/SignatureRequest.tsx
- Closes #1913
- Closes FE-1640
> fix: support hashable messages also in bytes format

- .changeset/flat-avocados-shop.md
- packages/connections/src/index.ts
- packages/types/src/accounts.ts
In this release, we:
- Tested releasing breaking changes.
This is a sample summary of a breakign change.
Sample text.
```typescript
const sampleCode = await testing.release();
```
> chore!: testing breaking changes

- .github/workflows/changesets-pr.yaml
In this release, we:
- Improved changeset PR workflow with better title formatting and automatic changelog prettification
Enhanced the changesets PR workflow by:
- Adding version detection to create more descriptive PR titles following the pattern `ci(release): \`v{version}\` @ \`{branch}\``
- Implementing automatic changelog prettification when changeset PRs are created
- Cleaning up workflow comments and redundant conditions
- Streamlining the workflow steps for better maintainability
These changes improve the release automation process by providing clearer PR titles and ensuring changelogs are properly formatted before review.
No breaking changes.
> chore: Improve changeset pr title and description

- .github/workflows/changesets-pr.yaml
In this release, we:
- Did this and that
> chore: add Github token

- .changeset/khaki-suns-swim.md
- packages/app/src/systems/Transaction/components/ActivityList/ActivityList.tsx
- packages/app/src/systems/Transaction/hooks/useAssetsAmount.tsx
- packages/app/src/systems/Transaction/hooks/useBridgeLink.tsx
- packages/app/src/systems/Transaction/hooks/useSimplifiedTransaction.tsx
- packages/app/src/systems/Transaction/hooks/useTxMetadata.tsx
This TEST includes changes in the main /app.
> chore: testing release note
